name: remedi_kopo
description: Search for Korean postal address. Fork of Kopo package with our web hosting for front-end.
version: 0.0.1
homepage: 'https://github.com/studio-b-co-kr/remedi_flutter_plugins'
repository: 'https://github.com/studio-b-co-kr/remedi_flutter_plugins'

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
