name: remedi_linker
version: 0.0.2
homepage: 'https://github.com/studio-b-co-kr/remedi_flutter_plugins'
repository: 'https://github.com/studio-b-co-kr/remedi_flutter_plugins'


environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
